language: android

android:
  components:
    - build-tools-29.0.2
    - android-28
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    
jdk:
  - openjdk8

dist: trusty

before_script:
  - yes | sdkmanager "build-tools;28.0.3"

script:
  - ./gradlew assembleDebug testDebugUnitTest
